[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "target/forge"
cache_path = "target/forge-cache"
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
build_info = true
extra_output = ["storageLayout"]
remappings = ["@openzeppelin/=node_modules/@openzeppelin/"]

[profile.fork]
test = "contracts/fork"
